spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE